---
version: 2
jobs:
  build:
    docker:
      - image: node:8
    working_directory: /tmp/http-call
    steps:
      - checkout
      - restore_cache:
          keys:
            - http-call-{{ .Branch }}-{{checksum "package.json"}}
            - http-call-{{ .Branch }}
            - http-call-master
      - run: yarn
      - run: yarn test -- --coverage
      - run: yarn run coverage
      - save_cache:
          key: http-call-{{ .Branch}}-{{checksum "package.json"}}
          paths:
            - /tmp/http-call/node_modules
            - /usr/local/share/.cache/yarn
